name: Build APK Godot 4

on:
  push:
    branches: [ "main", "master" ]

jobs:
  export-android:
    runs-on: ubuntu-latest
    container:
      # Versi sudah saya sesuaikan dengan milikmu
      image: barichello/godot-ci:4.7.2 
    steps:
      - name: Ambil File dari GitHub
        uses: actions/checkout@v3

      - name: Ekstrak ZIP
        # PENTING: Ubah tulisan "nama_game_kamu.zip" menjadi nama file zip yang kamu upload!
        run: |
          unzip tp-drift-upgraded.zip -d project/
          
      - name: Proses Export ke APK
        run: |
          cd project
          mkdir -p hasil_apk
          
          # Membuat debug keystore otomatis (kunci wajib untuk Android)
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999
          
          # Membaca aset game (Perintah khusus Godot 4)
          godot --headless --editor --quit || true
          
          # Mengubah menjadi APK (Perintah khusus Godot 4)
          godot --headless --export-debug "Android" hasil_apk/game.apk

      - name: Simpan APK agar bisa didownload
        uses: actions/upload-artifact@v3
        with:
          name: ESS-RACING-ALPHA
          path: project/hasil_apk/
